version: '3.10'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data_app:/app/data_app
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app/Scouting_Assistant.py
